# Mathematics & Statistics Knowledge Base - 10 Q&A pairs

MATH_QA = [
    {
        "question": "What is calculus and what are its main branches?",
        "answer": "**Calculus** is the mathematical study of continuous change:\n\n**Differential Calculus:**\n• Studies rates of change (derivatives)\n• Finds slopes of curves at any point\n• Applications: Optimization, physics, economics\n• Key concept: dy/dx = limit of Δy/Δx as Δx → 0\n\n**Integral Calculus:**\n• Studies accumulation of quantities (integrals)\n• Finds areas under curves\n• Applications: Area, volume, probability\n• Key concept: ∫f(x)dx = antiderivative of f(x)\n\n**Fundamental Theorem of Calculus:**\n• Links differentiation and integration\n• ∫[a to b] f'(x)dx = f(b) - f(a)\n\n**Applications:** Physics (motion), Engineering (optimization), Economics (marginal analysis)"
    },
    {
        "question": "Explain linear algebra and its importance",
        "answer": "**Linear Algebra** deals with vectors, matrices, and linear transformations:\n\n**Key Concepts:**\n• **Vectors:** Quantities with magnitude and direction\n• **Matrices:** Rectangular arrays of numbers\n• **Linear Transformations:** Functions preserving vector operations\n• **Vector Spaces:** Sets closed under addition and scalar multiplication\n\n**Matrix Operations:**\n• Addition: Element-wise addition\n• Multiplication: Row × Column dot products\n• Transpose: Flip rows and columns\n• Inverse: A⁻¹ such that A × A⁻¹ = I\n\n**Applications:**\n• Computer Graphics (3D transformations)\n• Machine Learning (data representation)\n• Engineering (system analysis)\n• Economics (input-output models)\n\n**Eigenvalues & Eigenvectors:** Av = λv where λ is eigenvalue, v is eigenvector"
    },
    {
        "question": "What is probability and how do you calculate it?",
        "answer": "**Probability** measures the likelihood of events occurring:\n\n**Basic Definition:**\n• P(Event) = Number of favorable outcomes / Total possible outcomes\n• Range: 0 ≤ P(E) ≤ 1\n• P(E) = 0 (impossible), P(E) = 1 (certain)\n\n**Probability Rules:**\n• **Addition Rule:** P(A ∪ B) = P(A) + P(B) - P(A ∩ B)\n• **Multiplication Rule:** P(A ∩ B) = P(A) × P(B|A)\n• **Complement Rule:** P(A') = 1 - P(A)\n\n**Conditional Probability:**\n• P(A|B) = P(A ∩ B) / P(B)\n• Probability of A given B has occurred\n\n**Independence:**\n• Events A and B are independent if P(A|B) = P(A)\n• P(A ∩ B) = P(A) × P(B) for independent events\n\n**Applications:** Statistics, machine learning, risk analysis, gaming"
    },
    {
        "question": "Explain different types of probability distributions",
        "answer": "**Probability Distributions describe how probabilities are distributed:**\n\n**Discrete Distributions:**\n\n**1. Binomial Distribution:**\n• n independent trials, each with probability p\n• P(X = k) = C(n,k) × p^k × (1-p)^(n-k)\n• Example: Coin flips, pass/fail tests\n\n**2. Poisson Distribution:**\n• Events occurring in fixed time interval\n• P(X = k) = (λ^k × e^(-λ)) / k!\n• Example: Phone calls per hour, defects per batch\n\n**Continuous Distributions:**\n\n**1. Normal Distribution:**\n• Bell-shaped curve, symmetric\n• Parameters: mean (μ) and standard deviation (σ)\n• 68-95-99.7 rule for standard deviations\n• Example: Heights, test scores, measurement errors\n\n**2. Uniform Distribution:**\n• Equal probability over interval [a,b]\n• P(x) = 1/(b-a) for a ≤ x ≤ b\n• Example: Random number generation\n\n**3. Exponential Distribution:**\n• Time between events in Poisson process\n• Example: Time between arrivals, component lifetimes"
    },
    {
        "question": "What is statistics and what are its main types?",
        "answer": "**Statistics** is the science of collecting, analyzing, and interpreting data:\n\n**Descriptive Statistics:**\n• Summarizes and describes data\n• **Measures of Central Tendency:**\n  - Mean: Average value\n  - Median: Middle value when sorted\n  - Mode: Most frequent value\n• **Measures of Spread:**\n  - Range: Max - Min\n  - Variance: Average squared deviation\n  - Standard Deviation: √Variance\n\n**Inferential Statistics:**\n• Makes predictions about populations from samples\n• **Hypothesis Testing:** Test claims about parameters\n• **Confidence Intervals:** Range of plausible values\n• **Regression Analysis:** Relationship between variables\n\n**Types of Data:**\n• **Quantitative:** Numerical (height, weight)\n• **Qualitative:** Categorical (color, gender)\n• **Discrete:** Countable (number of students)\n• **Continuous:** Measurable (temperature, time)"
    },
    {
        "question": "How do you perform hypothesis testing?",
        "answer": "**Hypothesis Testing** is a statistical method to test claims:\n\n**Steps:**\n\n**1. State Hypotheses:**\n• **Null Hypothesis (H₀):** No effect/difference\n• **Alternative Hypothesis (H₁):** There is an effect\n• Example: H₀: μ = 50, H₁: μ ≠ 50\n\n**2. Choose Significance Level (α):**\n• Common values: 0.05, 0.01, 0.10\n• Probability of Type I error (rejecting true H₀)\n\n**3. Select Test Statistic:**\n• **t-test:** Compare means (small samples)\n• **z-test:** Compare means (large samples)\n• **Chi-square:** Test independence/goodness of fit\n• **F-test:** Compare variances\n\n**4. Calculate p-value:**\n• Probability of observing data if H₀ is true\n\n**5. Make Decision:**\n• If p-value < α: Reject H₀\n• If p-value ≥ α: Fail to reject H₀\n\n**Types of Errors:**\n• **Type I:** Reject true H₀ (false positive)\n• **Type II:** Accept false H₀ (false negative)"
    },
    {
        "question": "What is regression analysis and its types?",
        "answer": "**Regression Analysis** studies relationships between variables:\n\n**Simple Linear Regression:**\n• One predictor variable\n• Equation: y = β₀ + β₁x + ε\n• β₀: y-intercept, β₁: slope, ε: error term\n• Example: Predicting salary from experience\n\n**Multiple Linear Regression:**\n• Multiple predictor variables\n• Equation: y = β₀ + β₁x₁ + β₂x₂ + ... + βₙxₙ + ε\n• Example: Predicting house price from size, location, age\n\n**Key Metrics:**\n• **R-squared:** Proportion of variance explained\n• **Adjusted R-squared:** Accounts for number of predictors\n• **p-values:** Significance of coefficients\n• **Residuals:** Difference between actual and predicted\n\n**Assumptions:**\n• Linearity: Relationship is linear\n• Independence: Observations are independent\n• Homoscedasticity: Constant variance\n• Normality: Residuals are normally distributed\n\n**Other Types:**\n• **Logistic Regression:** Binary outcomes\n• **Polynomial Regression:** Non-linear relationships\n• **Ridge/Lasso:** Regularized regression"
    },
    {
        "question": "Explain discrete mathematics and its applications",
        "answer": "**Discrete Mathematics** deals with countable, distinct objects:\n\n**Key Areas:**\n\n**1. Set Theory:**\n• Collections of distinct objects\n• Operations: Union (∪), Intersection (∩), Complement (')\n• Venn diagrams for visualization\n\n**2. Logic:**\n• **Propositional Logic:** True/false statements\n• **Predicate Logic:** Quantified statements\n• Logical operators: AND (∧), OR (∨), NOT (¬), IMPLIES (→)\n\n**3. Combinatorics:**\n• **Permutations:** Order matters, P(n,r) = n!/(n-r)!\n• **Combinations:** Order doesn't matter, C(n,r) = n!/(r!(n-r)!)\n• **Pigeonhole Principle:** If n items in m containers, at least one has ≥⌈n/m⌉ items\n\n**4. Graph Theory:**\n• Vertices connected by edges\n• Applications: Social networks, routing, scheduling\n\n**5. Number Theory:**\n• Properties of integers\n• Prime numbers, modular arithmetic\n\n**Applications:** Computer science algorithms, cryptography, database design"
    },
    {
        "question": "What are matrices and their operations?",
        "answer": "**Matrices** are rectangular arrays of numbers arranged in rows and columns:\n\n**Matrix Notation:**\n• A = [aᵢⱼ] where i = row, j = column\n• Dimensions: m × n (m rows, n columns)\n\n**Basic Operations:**\n\n**1. Addition/Subtraction:**\n• Same dimensions required\n• Element-wise operation: (A ± B)ᵢⱼ = aᵢⱼ ± bᵢⱼ\n\n**2. Scalar Multiplication:**\n• Multiply each element by scalar: (kA)ᵢⱼ = k × aᵢⱼ\n\n**3. Matrix Multiplication:**\n• A(m×n) × B(n×p) = C(m×p)\n• cᵢⱼ = Σ(aᵢₖ × bₖⱼ) for k=1 to n\n• **Not commutative:** AB ≠ BA generally\n\n**Special Matrices:**\n• **Identity Matrix (I):** Diagonal of 1s, rest 0s\n• **Zero Matrix:** All elements are 0\n• **Transpose (Aᵀ):** Rows become columns\n• **Inverse (A⁻¹):** AA⁻¹ = I (if exists)\n\n**Applications:** Computer graphics, solving linear systems, data transformation"
    },
    {
        "question": "How do you solve systems of linear equations?",
        "answer": "**Systems of Linear Equations** can be solved using various methods:\n\n**Matrix Form:** Ax = b\n• A: coefficient matrix\n• x: variable vector\n• b: constant vector\n\n**Solution Methods:**\n\n**1. Gaussian Elimination:**\n• Transform to row echelon form\n• Use back substitution\n• Systematic elimination of variables\n\n**2. Matrix Inverse Method:**\n• If A⁻¹ exists: x = A⁻¹b\n• Only works for square, non-singular matrices\n\n**3. Cramer's Rule:**\n• x₁ = det(A₁)/det(A)\n• Replace column i with b vector\n• Only for square systems with det(A) ≠ 0\n\n**4. Substitution Method:**\n• Solve one equation for one variable\n• Substitute into other equations\n• Good for small systems\n\n**5. Elimination Method:**\n• Add/subtract equations to eliminate variables\n• Systematic reduction\n\n**Solution Types:**\n• **Unique Solution:** One solution exists\n• **No Solution:** Inconsistent system\n• **Infinite Solutions:** Dependent equations"
    }
]
